stages:
  - test
  - publish

include:
- template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  image: golang:1.17-alpine
  script:
    - go mod tidy
    - go test ./... -coverprofile coverage.txt -covermode count
    - go run gotest.tools/gotestsum --junitfile report.xml format testname
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > cobertura.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml

sonar:
  stage: test
  image: sonarsource/sonar-scanner-cli
  script:
    - |
      sonar-scanner \
      -Dsonar.organization=mikeyglitz \
      -Dsonar.projectKey=mikeyglitz_gohealth \
      -Dsonar.sources=. \
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.token=$SONAR_TOKEN